services:
  postgres:
    image: postgres:16
    container_name: ai_interview_postgres
    environment:
      POSTGRES_DB: ai_interview
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - ai_interview_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ai_interview_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - ai_interview_network
    restart: unless-stopped

volumes:
  pg:
    driver: local

networks:
  ai_interview_network:
    driver: bridge
